OpenStackweb/summit-api

app/ModelSerializers/Summit/Presentation/AdminSummitEventCSVSerializer.php
ref: https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2651444&fileview=grid
=> Add Activity Type to Activity CSV export

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitAttendeesApiController.php, app/Jobs/Emails/Registration/Attendees/SummitAttendeeAllTicketsEditionEmail.php, app/Services/Model/AttendeeService.php, app/Services/Model/Strategies/EmailActions/AbstractEmailAction.php, app/Services/Model/Strategies/EmailActions/EmailActionsStrategyFactory.php, app/Services/Model/Strategies/EmailActions/IEmailActionsStrategyFactory.php, app/Services/Model/Strategies/EmailActions/SummitAttendeeAllCurrentTicketsEmailStrategy.php, app/Services/Model/Strategies/EmailActions/SummitAttendeeTicketEmailStrategy.php, database/migrations/model/Version20220207195239.php, database/migrations/model/Version20220207195617.php, tests/AttendeeServiceTest.php, tests/InsertSummitTestData.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2785124&fileview=grid
=> add list of events the attendee is registered for

app/Console/Commands/PresentationMediaUploadsRegenerateTemporalLinks.php, app/Console/Kernel.php, app/Models/Foundation/Summit/Events/Presentations/Materials/PresentationMediaUpload.php, app/Models/Foundation/Summit/Repositories/IPresentationMediaUploadRepository.php, app/Repositories/RepositoriesProvider.php, app/Repositories/Summit/DoctrinePresentationMediaUploadRepository.php, app/Services/FileSystem/AbstractFileDownloadStrategy.php, app/Services/FileSystem/IFileDownloadStrategy.php, app/Services/Model/ISummitService.php, app/Services/Model/Imp/SummitService.php
for public storages media uploads
Change-Id: I38e19f0e84f3d00d5d60210e378dd43e40629975
=> Added new background job to recalculate temporal urls

app/Http/Controllers/Apis/Protected/Summit/Factories/SummitEventValidationRulesFactory.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2824427&fileview=grid
Database field type is mediumtext so it doesn't need to be modified
=> increase the abstract text length to 1600 characters

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitSelectionPlansApiController.php, app/Repositories/Summit/DoctrineSelectionPlanRepository.php, database/seeders/ApiEndpointsSeeder.php, routes/api_v1.php, tests/OAuth2SelectionPlansApiTest.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2860686&fileview=grid
=> selection plans fetching endpoint refactoring

app/Models/Foundation/Summit/SummitScheduleFilterElementConfig.php, database/migrations/model/Version20220328170502.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2870570&fileview=grid
=> TRACK_GROUPS schedule filter label tweak

app/ModelSerializers/Summit/Registration/SummitAttendeeTicketCSVSerializer.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2662645&fileview=grid
=> fix column mapping at csv serializer

app/Http/Controllers/Apis/Protected/Summit/Factories/SummitSelectionPlanValidationRulesFactory.php, app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitSelectionPlansApiController.php, app/ModelSerializers/Summit/SelectionPlanSerializer.php, app/Models/Foundation/Summit/SelectionPlan.php, database/migrations/model/Version20220331173736.php
added new attribute submission_period_disclaimer ( string )
ref https://tipit.avaza.com/project/view/304272#!tab=task-pane&task=2876261
Change-Id: I8a214f9a6cb340300e70e9ed19698d3e13980d70
=> Updated selection plan entity

app/Services/Model/AttendeeService.php, app/Services/Model/Imp/SummitOrderService.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2846590&fileview=grid
=> fix attendee's member loss on ticket assignment and reasignment

app/Http/Controllers/Apis/Protected/Summit/Factories/SummitSelectionPlanValidationRulesFactory.php, app/Jobs/Emails/PresentationSubmissions/PresentationCreatorNotificationEmail.php, app/Jobs/Emails/PresentationSubmissions/PresentationModeratorNotificationEmail.php, app/Jobs/Emails/PresentationSubmissions/PresentationSpeakerNotificationEmail.php, app/ModelSerializers/Summit/SelectionPlanSerializer.php, app/Models/Foundation/Summit/Factories/SummitSelectionPlanFactory.php, app/Models/Foundation/Summit/SelectionPlan.php, database/migrations/model/Version20220404193539.php, tests/InsertSummitTestData.php, tests/OAuth2SummitSelectionPlansApiTest.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2875188&fileview=grid
=> customize email templates by selection plan

app/Services/Model/Imp/SummitSelectionPlanService.php, database/migrations/model/Version20220412182357.php, resources/lang/en/not_found_errors.php, resources/lang/en/validation_errors.php, tests/OAuth2SummitSelectionPlansApiTest.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2892481&fileview=grid
=> Only allow PresentationType instances to be added to selection plans

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitOrderExtraQuestionTypeApiController.php, app/Jobs/Emails/Registration/ExternalIngestion/SuccessfulIIngestionEmail.php, app/Jobs/IngestSummitExternalRegistrationData.php, app/Models/Foundation/Main/ExtraQuestions/ExtraQuestionType.php, app/Models/Foundation/Summit/Factories/SummitAttendeeFactory.php, app/Models/Foundation/Summit/Registration/ExtraQuestions/SummitOrderExtraQuestionType.php, app/Models/Foundation/Summit/Repositories/ISummitAttendeeRepository.php, app/Models/Foundation/Summit/Summit.php, app/Repositories/Summit/DoctrineSummitAttendeeRepository.php, app/Services/Apis/EventbriteAPI.php, app/Services/Apis/ExternalRegistrationFeeds/IExternalRegistrationFeed.php, app/Services/Apis/ExternalRegistrationFeeds/IExternalRegistrationFeedResponse.php, app/Services/Apis/ExternalRegistrationFeeds/implementations/EventbriteRegistrationFeed.php, app/Services/Apis/ExternalRegistrationFeeds/implementations/EventbriteResponse.php, app/Services/Apis/IEventbriteAPI.php, app/Services/Model/ISummitOrderExtraQuestionTypeService.php, app/Services/Model/Imp/RegistrationIngestionService.php, app/Services/Model/Imp/SummitOrderExtraQuestionTypeService.php, app/Services/Model/Imp/SummitOrderService.php, app/Services/Model/Imp/SummitTicketTypeService.php, database/migrations/model/Version20220404193539.php, database/migrations/model/Version20220405205916.php, database/migrations/model/Version20220418192910.php, database/migrations/model/Version20220420155435.php, database/migrations/model/Version20220420171938.php, database/migrations/model/Version20220420171940.php, database/seeders/ApiEndpointsSeeder.php, resources/lang/en/validation_errors.php, routes/api_v1.php, tests/ExternalRegistrationIngestionTest.php
WIP
Change-Id: Iad8914974c80908cabfe36197d38be0d02d875d0
=> Registration Eventbrite ingestion extra questions

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitRegistrationCompaniesApiController.php, app/Models/Foundation/Summit/Repositories/ISummitRepository.php, app/Models/Foundation/Summit/Summit.php, app/Repositories/Summit/DoctrineSummitRepository.php, app/Services/Model/ISummitService.php, app/Services/Model/Imp/SummitService.php, database/migrations/model/Version20220418172350.php, database/seeders/ApiEndpointsSeeder.php, routes/api_v1.php, tests/OAuth2SummitApiTest.php, tests/OAuth2SummitRegistrationCompaniesApiTest.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2896644&fileview=grid
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2896704&fileview=grid
=> Summit-Registration_Companies model relation and crud endpoints

app/Services/Model/Imp/SummitService.php
ref https://tipit.avaza.com/project/view/304272#!tab=task-pane&task=2896768
=> Validate if the company to add to the summit is already associated

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitOrdersApiController.php, app/Jobs/Emails/Registration/Attendees/InviteAttendeeTicketEditionMail.php, app/Jobs/Emails/Registration/Attendees/RevocationTicketEmail.php, app/Jobs/Emails/Registration/Attendees/SummitAttendeeTicketEmail.php, app/Jobs/Emails/Registration/Refunds/SummitOrderRefundRequestAdmin.php, app/Jobs/Emails/Registration/Refunds/SummitOrderRefundRequestOwner.php, app/Jobs/Emails/Registration/Refunds/SummitTicketRefundRequestAdmin.php, app/Jobs/Emails/Registration/Refunds/SummitTicketRefundRequestOwner.php, app/Jobs/Emails/Registration/RegisteredMemberOrderPaidMail.php, app/Jobs/Emails/Registration/Reminders/SummitOrderReminderEmail.php, app/Jobs/Emails/Registration/Reminders/SummitTicketReminderEmail.php, app/ModelSerializers/Summit/Registration/SummitOrderBaseSerializer.php, app/Models/Foundation/Summit/Factories/SummitOrderFactory.php, app/Models/Foundation/Summit/Registration/SummitOrder.php, app/Services/Model/Imp/SummitOrderService.php, database/migrations/model/Version20220420184724.php, tests/InsertOrdersTestData.php, tests/OAuth2SummitOrdersApiTest.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2896766&fileview=grid
=> OwnerCompanyID integration to SummitOrder model

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitDocumentsApiController.php, app/ModelSerializers/Summit/SummitDocumentSerializer.php, app/Models/Foundation/Summit/SummitDocument.php, app/Repositories/Summit/DoctrineSummitDocumentRepository.php, app/Services/Model/Imp/SummitDocumentService.php, database/migrations/model/Version20220427192118.php
Change-Id: I60f8d78456842344f23b8bfe492ce9027fdd3646
ref https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=2907376
=> Added summit documents per selection type

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitTracksApiController.php, app/ModelSerializers/Summit/Presentation/PresentationCategorySerializer.php, app/Models/Foundation/Main/ExtraQuestions/ExtraQuestionType.php, app/Models/Foundation/Summit/Events/Presentations/PresentationCategory.php, app/Models/Foundation/Summit/Summit.php, app/Repositories/Summit/DoctrineSummitTrackRepository.php, app/Services/Model/Imp/SummitTrackService.php, database/migrations/model/Version20220427203735.php, tests/OAuth2TracksApiTest.php
Change-Id: I1d0a54919ae918db83a19a8ccdd308d8c090d53c
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2907374&fileview=grid
=> Updated track entitiy added custom ordering

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitBadgeScanApiController.php, app/Services/Model/AttendeeService.php, app/Services/Model/IAttendeeService.php, app/Services/Model/ISponsorUserInfoGrantService.php, database/seeders/ApiEndpointsSeeder.php, routes/api_v1.php, tests/InsertSummitTestData.php, tests/OAuth2SummitBadgeScanApiControllerTest.php, tests/OAuth2SummitScheduleSettingsApiTest.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2916710&fileview=grid
=> check in endpoint

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitTrackChairRatingTypesApiController.php, app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitTrackChairScoreTypesApiController.php, tests/OAuth2SummitTrackChairsRankingApiTest.php
requested by tix https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2929960&fileview=grid
=> Fix expands on ranking types crud

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitRegistrationCompaniesApiController.php, app/Jobs/ProcessRegistrationCompaniesDataImport.php, app/Services/Model/ISummitService.php, app/Services/Model/Imp/SummitService.php, database/seeders/ApiEndpointsSeeder.php, routes/api_v1.php
added new endpoint
POST /api/v1/summits/{id}/registration-companies/csv
param file ( CSV )
required columns [name]
associate companies on csv to summit as registration companies
( if the company does not exists, create it )
Change-Id: Id4895a2b9bc8e17e2dd800fde043e3425647d5a7
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2939128&fileview=grid
=> Registration Companies Import

app/Http/Controllers/Apis/Protected/Summit/Factories/PaymentGatewayProfileValidationRulesFactory.php, app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitOrdersApiController.php, app/ModelSerializers/SerializerRegistry.php, app/ModelSerializers/Summit/AdminLawPayPaymentProfileSerializer.php, app/ModelSerializers/Summit/LawPayPaymentProfileSerializer.php, app/ModelSerializers/Summit/PaymentGatewayProfileSerializer.php, app/Models/Foundation/Summit/Factories/PaymentGatewayProfileFactory.php, app/Models/Foundation/Summit/Registration/Payment/IPaymentConstants.php, app/Models/Foundation/Summit/Registration/Payment/LawPayPaymentProfile.php, app/Models/Foundation/Summit/Registration/Payment/PaymentGatewayProfile.php, app/Models/Foundation/Summit/Registration/Payment/StripePaymentProfile.php, app/Services/Apis/IPaymentGatewayAPI.php, app/Services/Apis/PaymentGateways/ILawPayApiChargeStatus.php, app/Services/Apis/PaymentGateways/ILawPayApiEventType.php, app/Services/Apis/PaymentGateways/LawPayApi.php, app/Services/Apis/PaymentGateways/StripeApi.php, app/Services/Model/Imp/SummitOrderService.php, composer.json, composer.lock, database/migrations/model/Version20220620181650.php, database/migrations/model/Version20220620181652.php, database/migrations/model/Version20220620182703.php, database/migrations/model/Version20220621150711.php
Integration with new Payment Profile LawPay
Change-Id: I74eca2e0658640790d8099d2e8bc7e06dfdd785e
=> LawPay API implementation

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitSpeakersApiController.php, app/Models/Foundation/Summit/Speakers/PresentationSpeaker.php, app/Repositories/DoctrineRepository.php, app/Repositories/Summit/DoctrineSpeakerRepository.php, tests/OAuth2SummitSpeakersApiTest.php
Refactored Doctrine Speaker Repo to DQL
Change-Id: I88fc89e7a9388bc5074adbea740deb6feefa75b8
ref https://tipit.avaza.com/project/view/304272#!tab=task-pane&groupby=ProjectSection&view=vertical&task=2948603&fileview=grid
=> Fixed speakers filters

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitOrdersApiController.php, app/Services/Model/Imp/SummitOrderService.php, routes/api_v1.php
* added permission checking
* refactoring
Change-Id: Ib5af4f77f0550fcc52ddc181426b9e801e834573
ref https://tipit.avaza.com/project/view/312153#!tab=task-pane&groupby=ProjectSection&view=vertical&task=2974592&fileview=grid
=> Reassign ticket permissions for Invitation only audience

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitSpeakersApiController.php, app/Http/Controllers/Apis/Protected/Summit/Traits/ParametrizedGetAll.php, app/Http/Utils/Filters/DoctrineFilterMapping.php, app/Http/Utils/Filters/Filter.php, app/Http/Utils/Filters/FilterParser.php, app/Jobs/Emails/AbstractEmailJob.php, app/Jobs/Emails/PresentationSubmissions/SelectionProcess/PresentationSpeakerSelectionProcessAcceptedAlternateEmail.php, app/Jobs/Emails/PresentationSubmissions/SelectionProcess/PresentationSpeakerSelectionProcessAcceptedOnlyEmail.php, app/Jobs/Emails/PresentationSubmissions/SelectionProcess/PresentationSpeakerSelectionProcessAcceptedRejectedEmail.php, app/Jobs/Emails/PresentationSubmissions/SelectionProcess/PresentationSpeakerSelectionProcessAlternateOnlyEmail.php, app/Jobs/Emails/PresentationSubmissions/SelectionProcess/PresentationSpeakerSelectionProcessAlternateRejectedEmail.php, app/Jobs/Emails/PresentationSubmissions/SelectionProcess/PresentationSpeakerSelectionProcessEmail.php, app/Jobs/Emails/PresentationSubmissions/SelectionProcess/PresentationSpeakerSelectionProcessEmailFactory.php, app/Jobs/Emails/PresentationSubmissions/SelectionProcess/PresentationSpeakerSelectionProcessRejectedOnlyEmail.php, app/ModelSerializers/Summit/Presentation/SpeakerPresentationEmailSerializer.php, app/ModelSerializers/Summit/Speakers/AdminPresentationSpeakerCSVSerializer.php, app/ModelSerializers/Summit/Speakers/PresentationSpeakerBaseSerializer.php, app/ModelSerializers/Summit/Speakers/PresentationSpeakerSerializer.php, app/Models/Foundation/Main/Member.php, app/Models/Foundation/Summit/Speakers/PresentationSpeaker.php, app/Repositories/DoctrineRepository.php, app/Repositories/Summit/DoctrineSpeakerRepository.php, app/Services/Model/Imp/SpeakerService.php, app/Services/Model/Strategies/EmailActions/SpeakerActionsEmailStrategy.php, tests/InsertSummitTestData.php, tests/OAuth2SummitSpeakersApiTest.php
Applying Filters to activities
Change-Id: I5f0642cd82cf9e3acb2fc4dbdaf7c0835a447768
=> Speaker Email Grid

app/Models/Foundation/Main/Companies/Company.php, tests/OAuth2SummitRegistrationCompaniesApiTest.php
ref https://tipit.avaza.com/project/view/304272#!tab=task-pane&task=2939128
=> fix company model & add ingest test case

app/Http/Controllers/Apis/Protected/Main/OAuth2SponsoredProjectApiController.php, app/ModelSerializers/Companies/SponsoredProjectSerializer.php, app/Models/Foundation/Main/Companies/SponsoredProject.php, app/Repositories/Main/DoctrineSponsoredProjectRepository.php, app/Services/Model/Imp/SponsoredProjectService.php, database/migrations/model/Version20220718214726.php, database/seeders/ApiEndpointsSeeder.php, routes/api_v1.php, tests/OAuth2SponsoredProjectsApiTest.php, tests/SponsoredProjectModelTest.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2824443&fileview=grid
=> Sponsored sub projects support

app/Services/Model/Imp/SummitRegistrationInvitationService.php, tests/OAuth2SummitRegistrationInvitationApiControllerTest.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2993091&fileview=grid
=> Update existing invitations during ingest

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitSpeakersApiController.php, app/Repositories/Summit/DoctrineSpeakerRepository.php, tests/OAuth2SummitSpeakersApiTest.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3008859&fileview=grid
=> Add Search by Speaker ID and Member ID to Speakers

app/Http/Controllers/Apis/Protected/Summit/Strategies/events/RetrieveSummitEventsStrategy.php, app/ModelSerializers/AbstractMemberSerializer.php, app/Models/Foundation/Main/Member.php, app/Repositories/Summit/DoctrineSummitEventRepository.php, app/Services/Model/Imp/MemberService.php, database/migrations/model/Version20220809200051.php
* created_by_company
* update member model to retrieve company from IDP profile
Change-Id: Icd99a3c0998f6656cdf0001a070b9ea355d2da23
=> Added filters

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitApiController.php, app/Repositories/Summit/DoctrineSpeakerRepository.php, tests/OAuth2SummitSpeakersApiTest.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3008859&fileview=grid
=> Add Search by Speaker ID and Member ID to Summit Featured Speakers

app/Http/Controllers/Apis/Protected/Summit/Factories/SummitEventValidationRulesFactory.php, app/Http/Controllers/Apis/Protected/Summit/Strategies/events/RetrieveSummitEventsStrategy.php, app/ModelSerializers/Summit/SummitEventSerializer.php, app/Models/Foundation/Summit/Events/SummitEvent.php, app/Repositories/Summit/DoctrineSummitEventRepository.php, app/Services/Model/Imp/SummitService.php, database/migrations/model/Version20220812151207.php, tests/OAuth2SummitEventsApiTest.php, tests/SummitEventModelTest.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3012743&fileview=grid
=> Added duration to SummitEvent model

app/Services/Model/Imp/SummitMetricService.php, tests/OAuth2SummitMetricsApiControllerTest.php
=> relax ingress validation

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitMediaUploadTypeApiController.php, app/ModelSerializers/Summit/SummitMediaUploadTypeSerializer.php, app/Models/Foundation/Summit/Events/Presentations/Presentation.php, app/Models/Foundation/Summit/Events/Presentations/PresentationType.php, app/Models/Foundation/Summit/Factories/SummitMediaUploadTypeFactory.php, app/Models/Foundation/Summit/MediaUploads/SummitMediaUploadType.php, app/Services/Model/Imp/PresentationService.php, database/migrations/model/Version20220830224755.php, database/migrations/model/Version20220901205619.php, tests/OAuth2SummitMediaUploadTypeApiControllerTest.php, tests/PresentationMediaUploadsTests.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2203359&fileview=grid
=> Min and max media upload constraints by media upload type

database/migrations/model/Version20220914190758.php
=> set default max media upload qty to 1

app/Http/Controllers/Apis/Protected/Main/OAuth2TagsApiController.php, app/Services/Model/ITagService.php, app/Services/Model/Imp/TagService.php, database/seeders/ApiEndpointsSeeder.php, routes/api_v1.php, tests/OAuth2TagsApiTest.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3047238&fileview=grid
=> Tags CRUD endpoints

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitRegistrationInvitationApiController.php, app/Repositories/Summit/DoctrineSummitRegistrationInvitationRepository.php
ref https://tipit.avaza.com/project/view/203215#!tab=task-pane&task=3045398 
=> add new filter by ticket types to registration invitations

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitRegistrationInvitationApiController.php, app/Jobs/Emails/Registration/Invitations/ProcessRegistrationInvitationsJob.php, app/ModelSerializers/Summit/Registration/SummitRegistrationInvitationSerializer.php, app/Models/Foundation/Summit/Registration/SummitRegistrationInvitation.php, app/Repositories/Summit/DoctrineSummitRegistrationInvitationRepository.php, app/Services/Model/Imp/SummitRegistrationInvitationService.php, database/migrations/model/Version20220914190758.php, database/migrations/model/Version20220926134809.php, database/migrations/model/Version20220926134810.php, tests/OAuth2SummitRegistrationInvitationApiControllerTest.php
* updated invitation to have tags collection
* added new filtering conditions
- tags ['@@','==','=@']
- tags_id ['==']
Change-Id: Ib1e9f25944d7fde31d04d73b2f17b94a1c43f741
=> Updated Registration Invitation Entity to support tags

app/Http/Controllers/Apis/Protected/Summit/Factories/SummitValidationRulesFactory.php, app/ModelSerializers/Summit/SummitSerializer.php, app/Models/Foundation/Summit/Factories/SummitFactory.php, app/Models/Foundation/Summit/Summit.php, app/Services/Model/Imp/SummitOrderService.php, database/migrations/model/Version20221004141001.php
* added time limit ( optional)
summit.registration_allowed_refund_request_till_date
Change-Id: Ie624f537c3551e113995ca435f4374fae770ee9c
=> Updated Request Refund Rules

app/Services/Model/Imp/SummitTrackService.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3069636&fileview=grid
=> add svg as allowed extension

Libs/Utils/PunnyCodeHelper.php, app/Http/Utils/Filters/DoctrineCollectionFieldsFilterMapping.php, app/Http/Utils/Filters/DoctrineFilterMapping.php, app/Http/Utils/Filters/DoctrineHavingFilterMapping.php, app/Http/Utils/Filters/DoctrineInstanceOfFilterMapping.php, app/Http/Utils/Filters/DoctrineJoinFilterMapping.php, app/Http/Utils/Filters/DoctrineLeftJoinFilterMapping.php, app/Http/Utils/Filters/DoctrineSwitchFilterMapping.php, app/Http/Utils/Filters/Filter.php, app/Http/Utils/Filters/FilterElement.php, app/Http/Utils/Filters/IQueryApplyable.php, app/Models/Foundation/Main/Member.php, app/Models/Foundation/Summit/Registration/Attendees/SummitAttendee.php, app/Models/Foundation/Summit/Registration/SummitOrder.php, app/Models/Foundation/Summit/Repositories/ISpeakerRepository.php, app/Models/Foundation/Summit/Speakers/PresentationSpeaker.php, app/Models/Foundation/Summit/Speakers/SpeakerRegistrationRequest.php, app/Repositories/Summit/DoctrineMemberRepository.php, app/Repositories/Summit/DoctrineSpeakerRepository.php, app/Repositories/Summit/DoctrineSummitAttendeeRepository.php, tests/FilterParserTest.php, tests/OAuth2SummitEventsApiTest.php, tests/OAuth2SummitSpeakersApiTest.php
Change-Id: I86d7f90fc560fb56c973787d71a042d0688b31ce
=> Punny code updates

app/ModelSerializers/Summit/Registration/SummitRegistrationInvitationCSVSerializer.php, tests/OAuth2SummitRegistrationInvitationApiControllerTest.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3069582&fileview=grid
=> Add tags & allowed_ticket_types to csv serializer

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitBadgeScanApiController.php, tests/OAuth2SummitBadgeScanApiControllerTest.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3062738&fileview=grid
=> strip HTML tags from extra questions label

database/migrations/model/Version20221012133111.php, tests/OAuth2AttendeesApiTest.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3061395&fileview=grid
=> Change Attendee.AdminNotes field collation to allow unicode

app/Services/Model/Imp/SummitOrderService.php, tests/SummitOrderServiceTest.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2999191&fileview=grid
=> Skip ticket level reminder if the order and the ticket have the same owner

app/Services/Model/Imp/SummitSelectionPlanService.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3084246&fileview=grid
=> Validate presentation action type double assignment

app/Http/Controllers/Apis/Protected/Summit/Factories/SummitSponsorshipTypeValidationRules.php, app/Http/Controllers/Apis/Protected/Summit/OAuth2SponsorshipTypeApiController.php, app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitSelectionPlansApiController.php, app/ModelSerializers/Summit/SelectionPlanSerializer.php, app/ModelSerializers/Summit/SummitSponsorshipTypeSerializer.php, app/Models/Foundation/Main/Member.php, app/Models/Foundation/Summit/Factories/SummitSponsorshipTypeFactory.php, app/Models/Foundation/Summit/Repositories/ISelectionPlanRepository.php, app/Models/Foundation/Summit/SelectionPlan.php, app/Models/Foundation/Summit/SummitSponsorshipType.php, app/Repositories/Summit/DoctrineSelectionPlanRepository.php, app/Services/Model/ISummitSelectionPlanService.php, app/Services/Model/Imp/PresentationService.php, app/Services/Model/Imp/SummitSelectionPlanService.php, database/migrations/model/Version20221111143627.php, database/seeders/ApiEndpointsSeeder.php, routes/api_v1.php, tests/OAuth2SummitSelectionPlansApiTest.php
Change-Id: I80d679635ec70986bcc4ecfe667964839b2269ff
=> Private Selection Plans

app/Models/Foundation/Summit/Summit.php, app/Services/Model/Imp/SummitPresentationActionTypeService.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3084246&fileview=grid
=> Validate presentation action type double assignment to summit

app/Http/Controllers/Apis/Protected/Summit/Factories/SummitEventValidationRulesFactory.php, app/Http/Controllers/Apis/Protected/Summit/Factories/SummitSelectionPlanValidationRulesFactory.php, app/ModelSerializers/Summit/SelectionPlanSerializer.php, app/Models/Foundation/Summit/Events/Presentations/Presentation.php, app/Models/Foundation/Summit/Events/SummitEvent.php, app/Models/Foundation/Summit/Factories/PresentationFactory.php, app/Models/Foundation/Summit/Factories/SummitSelectionPlanFactory.php, app/Models/Foundation/Summit/SelectionPlan.php, app/Models/Foundation/Summit/SelectionPlanAllowedPresentationQuestion.php, app/Services/Model/Imp/PresentationService.php, app/Services/Model/Imp/SummitSelectionPlanService.php, database/migrations/model/Version20221125150407.php, database/migrations/model/Version20221125155044.php, tests/OAuth2SummitSelectionPlansApiTest.php
* allowed_presentation_questions (string array)
Change-Id: I25c5f7dc612d1cd585107bd1459d6a3185d50b87
=> Added new collection to selection plan

app/Http/Controllers/Apis/Protected/Summit/OAuth2PresentationApiController.php, app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitSelectionPlansApiController.php, app/Http/Controllers/Utils/RequestProcessor.php, app/Jobs/ProcessSelectionPlanAllowedMemberData.php, app/ModelSerializers/SerializerRegistry.php, app/ModelSerializers/Summit/SelectionPlanAllowedMemberSerializer.php, app/ModelSerializers/Summit/SelectionPlanSerializer.php, app/Models/Foundation/Main/Member.php, app/Models/Foundation/Summit/SelectionPlan.php, app/Models/Foundation/Summit/SelectionPlanAllowedMember.php, app/Repositories/Summit/DoctrineSelectionPlanRepository.php, app/Services/Model/ISummitSelectionPlanService.php, app/Services/Model/Imp/PresentationService.php, app/Services/Model/Imp/SummitSelectionPlanService.php, app/Services/Model/Imp/SummitSponsorService.php, app/Services/ModelServicesProvider.php, app/Services/Utils/CSVReader.php, database/migrations/model/Version20221128210849.php, database/seeders/ApiEndpointsSeeder.php, routes/api_v1.php, tests/CSVReaderTest.php, tests/InsertSummitTestData.php, tests/OAuth2SummitSelectionPlansApiTest.php
GET api/v1/summits/{id}/selection-plans/{selection_plan_id}/allowed-members
filter
email
POST api/v1/summits/{id}/selection-plans/{selection_plan_id}/allowed-members
payload
email
DELETE api/v1/summits/{id}/selection-plans/{selection_plan_id}/allowed-members
payload
email
POST api/v1/summits/{id}/selection-plans/{selection_plan_id}/allowed-members/csv
payload csv file
with unique colum email
Change-Id: I7a91bdb342334a8da81cd0e550102b27ec32ba5d
=> updated allowed members

app/Audit/AuditLogStrategy.php
Fix related to post-deploy error reported by @santipalenque 
=> Check null descriptions

app/ModelSerializers/Summit/Registration/BaseSummitAttendeeTicketSerializer.php, app/ModelSerializers/Summit/Registration/SummitOrderReservationSerializer.php, app/Models/Foundation/Summit/Registration/Attendees/SummitAttendeeTicket.php, app/Models/Foundation/Summit/Registration/Attendees/SummitAttendeeTicketTax.php, app/Models/Foundation/Summit/Registration/SummitOrder.php, app/Models/Foundation/Summit/Summit.php, app/Services/Apis/PaymentGateways/StripeApi.php, app/Services/Model/Imp/SummitTaxTypeService.php, app/Services/Model/Imp/SummitTicketTypeService.php
Change-Id: I75a85c2d9972bd90671c28694eaff96715334ebb
=> Fix on Stripe amount final rounding

app/ModelSerializers/Summit/Registration/BaseSummitAttendeeTicketSerializer.php, app/ModelSerializers/Summit/Registration/SummitAttendeeTicketTaxSerializer.php, app/ModelSerializers/Summit/Registration/SummitOrderBaseSerializer.php, app/ModelSerializers/Summit/Registration/SummitOrderReservationSerializer.php, app/Models/Foundation/Summit/Registration/Attendees/SummitAttendeeTicket.php, app/Models/Foundation/Summit/Registration/Attendees/SummitAttendeeTicketTax.php, app/Models/Foundation/Summit/Registration/SummitOrder.php, app/Models/Foundation/Summit/Registration/SummitRefundRequest.php, app/Models/Foundation/Summit/Registration/SummitTicketType.php, app/Models/Utils/Traits/FinancialTrait.php, app/Services/Apis/PaymentGateways/StripeApi.php, database/migrations/model/Version20221215191405.php
on applied_taxes collection
Change-Id: I8110d1299f03de74daa764373ecb788473c754cf
=> Updated SummitOrder and Ticket serializer to include taxes excerpt

app/Audit/ConcreteFormatters/EntityCollectionUpdateAuditLogFormatter.php, app/Audit/ConcreteFormatters/EntityDeletionAuditLogFormatter.php
ref https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=3084385
=> Log verbosity adjustments

app/Http/Controllers/Apis/Protected/Summit/Factories/Registration/PromoCodesValidationRulesFactory.php, app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitPromoCodesApiController.php, app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitTicketApiController.php, app/Models/Foundation/Summit/Factories/SummitPromoCodeFactory.php, app/Models/Foundation/Summit/Registration/PromoCodes/SummitRegistrationPromoCode.php, app/Repositories/Summit/DoctrineSummitAttendeeTicketRepository.php, app/Repositories/Summit/DoctrineSummitRegistrationPromoCodeRepository.php, database/migrations/model/Version20221221132905.php
promo.description ( sometimes|string|max:1024)
added new filter criteria  to
GET api/v1/summits/{id}/tickets
GET api/v1/summits/{id}/tickets/csv
* promo_code ['==','@@', '=@']
* promo_code_description ['@@', '=@']
added new filtering criteria for
GET api/v1/summits/{id}/promo-codes
GET api/v1/summits/{id}/promo-codes/csv
* description  ['@@', '=@']
Change-Id: I225505cd3db778f679b63edd85d5bde44cbfd593
=> Added new field to Promo code

app/Audit/ConcreteFormatters/ChildEntityFormatters/IChildEntityAuditLogFormatter.php, app/Audit/ConcreteFormatters/ChildEntityFormatters/PresentationActionAuditLogFormatter.php, app/Audit/ConcreteFormatters/ChildEntityFormatters/PresentationExtraQuestionAnswerAuditLogFormatter.php, app/Audit/ConcreteFormatters/EntityUpdateAuditLogFormatter.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3084387&fileview=grid
=> Bypass logging updates over the same value + args mismatching error fix

app/ModelSerializers/Summit/Registration/SummitAttendeeTicketCSVSerializer.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3040544&fileview=grid
=> Change "bought_date" to "purchase_date" in ticket list export

app/Audit/ConcreteFormatters/EntityUpdateAuditLogFormatter.php, app/Models/Utils/BaseEntity.php
Fix for reported error by Slack
=> Audit log formatter fix: object to string conversion error

app/Repositories/Summit/DoctrineMemberRepository.php
ref https://tipit.avaza.com/project/view/188885#!tab=task-pane&groupby=ProjectSection&view=vertical&task=3202877&fileview=grid
=> Created and Edited filter reinterpreted as DefaultTimeZone

app/Jobs/Emails/PresentationSubmissions/SelectionProcess/PresentationSpeakerSelectionProcessAcceptedAlternateEmail.php, app/Jobs/Emails/PresentationSubmissions/SelectionProcess/PresentationSpeakerSelectionProcessAcceptedOnlyEmail.php, app/Jobs/Emails/PresentationSubmissions/SelectionProcess/PresentationSpeakerSelectionProcessAcceptedRejectedEmail.php, app/Jobs/Emails/PresentationSubmissions/SelectionProcess/PresentationSpeakerSelectionProcessAlternateOnlyEmail.php, app/Jobs/Emails/PresentationSubmissions/SelectionProcess/PresentationSpeakerSelectionProcessAlternateRejectedEmail.php, app/Jobs/Emails/PresentationSubmissions/SelectionProcess/PresentationSpeakerSelectionProcessEmail.php, app/Jobs/Emails/PresentationSubmissions/SelectionProcess/PresentationSpeakerSelectionProcessEmailFactory.php, app/Jobs/Emails/PresentationSubmissions/SelectionProcess/PresentationSpeakerSelectionProcessRejectedOnlyEmail.php, app/Services/Model/Strategies/EmailActions/SpeakerActionsEmailStrategy.php
Change-Id: If8f92ce4a9657da98b435ffeb234ef21945e6d4c
=> Fixed nullable

app/Repositories/Main/DoctrineCompanyRepository.php, app/Services/Model/AttendeeService.php, app/Services/Model/Imp/CompanyService.php, app/Services/Model/Imp/RegistrationIngestionService.php, app/Services/Model/Imp/SummitOrderService.php, app/Services/Model/Imp/Traits/AttendeeCompany.php
Change-Id: Ib99274e07e6126c4bf81fcd1abc610322d56211f
=> Added creation of the attendee registration company if does not exists

app/Http/Controllers/Apis/Protected/Summit/Factories/SelectionPlanExtraQuestionValidationRulesFactory.php, app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitSelectionPlansApiController.php, app/ModelSerializers/Summit/AssignedSelectionPlanExtraQuestionTypeSerializer.php, app/Models/Foundation/Main/ExtraQuestions/ExtraQuestionAnswerHolder.php, app/Models/Foundation/Summit/Events/Presentations/Presentation.php, app/Models/Foundation/Summit/ExtraQuestions/AssignedSelectionPlanExtraQuestionType.php, app/Models/Foundation/Summit/Registration/Attendees/SummitAttendee.php, app/Services/Model/Imp/SelectionPlanOrderExtraQuestionTypeService.php, database/migrations/model/Version20230405154650.php, tests/ExtraQuestionTypeModelTest.php
Allow to edit
Change-Id: I1f1f27af57f3d1c3065fa1e75cf99d564347cad3
=> Selection Plan Extra Questions

app/Http/Controllers/Apis/Protected/Summit/Factories/SummitMediaUploadTypeValidationRulesFactory.php, app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitMediaUploadTypeApiController.php, app/ModelSerializers/Summit/SummitMediaUploadTypeSerializer.php, app/Models/Foundation/Summit/Factories/SummitMediaUploadTypeFactory.php, app/Models/Foundation/Summit/MediaUploads/SummitMediaUploadType.php, app/Services/Model/Imp/PresentationService.php, database/migrations/model/Version20230406210609.php
is_editable
Change-Id: I51e2934054f0361c826465976c5ad2c1cca25c42
=> Added new MediaUploadType Property

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitSignApiController.php, app/Http/Utils/Filters/FilterParser.php, app/ModelSerializers/SerializerRegistry.php, app/ModelSerializers/Summit/SummitSignSerializer.php, app/Models/Foundation/Summit/Repositories/ISummitSignRepository.php, app/Models/Foundation/Summit/Signs/SummitSign.php, app/Models/Foundation/Summit/Summit.php, app/Repositories/RepositoriesProvider.php, app/Repositories/Summit/DoctrineSummitSignRepository.php, app/Services/Model/ISummitSignService.php, app/Services/Model/Imp/SummitSignService.php, app/Services/ModelServicesProvider.php, database/migrations/model/Version20230420180010.php, database/seeders/ApiEndpointsSeeder.php, routes/api_v1.php, routes/public_api.php, tests/InsertSummitTestData.php, tests/OAuth2SummitSignApiTest.php
GET api/v1/summits/{summitid}/signs?filter=location_id==XYZ POST api/v1/summits/{summitid}/signs payload { location_id : XYZ , template: ''} PUT api/v1/summits/{summitid}/signs/{sign_id}
Change-Id: I5602ed9c493b75111231b7a8bf8814c5819c77fb
=> added new signs metamodel

app/Http/Controllers/Apis/Protected/Summit/Factories/SummitAbstractLocationValidationRulesFactory.php, app/Http/Controllers/Apis/Protected/Summit/Factories/SummitLocationValidationRulesFactory.php, app/ModelSerializers/Locations/SummitAbstractLocationSerializer.php, app/Models/Foundation/Summit/Factories/SummitLocationFactory.php, app/Models/Foundation/Summit/Locations/SummitAbstractLocation.php, app/Models/Foundation/Summit/Locations/SummitVenueRoom.php, app/Repositories/Summit/DoctrineSummitLocationRepository.php, app/Services/Model/Imp/AbstractPublishService.php, database/migrations/model/Version20230425143939.php, resources/lang/en/validation.php, tests/OAuth2SummitEventsApiTest.php, tests/OAuth2SummitLocationsApiTest.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3242656&stafilter=NotComplete&fileview=grid
=> locations time frame restriction

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitRegistrationInvitationApiController.php, app/Models/Foundation/Summit/Factories/SummitRegistrationInvitationFactory.php, app/Models/Foundation/Summit/Registration/SummitRegistrationInvitation.php, app/Services/Model/Imp/SummitRegistrationInvitationService.php, tests/OAuth2SummitRegistrationInvitationApiControllerTest.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=3269922&stafilter=NotComplete&fileview=grid
=> explicit mark RegistrationInvitation as complete

database/migrations/model/Version20230509123753.php
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3282108&stafilter=NotComplete&fileview=grid
=> increase SummitBadgeType description field size

app/Models/Foundation/Summit/Summit.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3281812&stafilter=NotComplete&fileview=grid
=> fix location removal from summit

app/Http/Controllers/Apis/Protected/Summit/Factories/Registration/SummitRegistrationInvitationValidationRulesFactory.php, app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitRegistrationInvitationApiController.php, app/ModelSerializers/Summit/Registration/SummitRegistrationInvitationSerializer.php, app/Models/Foundation/Summit/Factories/SummitRegistrationInvitationFactory.php, app/Models/Foundation/Summit/Registration/SummitRegistrationInvitation.php, app/Models/Foundation/Summit/Summit.php, app/Services/Model/ISummitRegistrationInvitationService.php, app/Services/Model/Imp/SummitRegistrationInvitationService.php, database/migrations/model/Version20230601143131.php, database/migrations/model/Version20230601143132.php
Change-Id: If7ba9c499f6c4fe5837e2a26cc65c605da3d5114
=> Registration Invitations - Acceptance Criteria

app/Models/Foundation/Summit/Factories/SummitOrderExtraQuestionTypeFactory.php, app/Services/Apis/ExternalRegistrationFeeds/IExternalRegistrationFeed.php, app/Services/Apis/ExternalRegistrationFeeds/implementations/EventbriteRegistrationFeed.php, app/Services/Apis/ExternalRegistrationFeeds/implementations/SamsungRegistrationFeed.php, app/Services/Apis/Samsung/PayloadParamNames.php, app/Services/Apis/Samsung/SamsungRecordSerializer.php, app/Services/Model/IRegistrationIngestionService.php, app/Services/Model/Imp/RegistrationIngestionService.php, app/Services/Model/Strategies/TicketFinder/Strategies/TicketFinderByExternalFeedStrategy.php
* added extra questions mapping
Change-Id: I9087eafe854784ba9e007102aec01f2982f5f7e5
=> Samsung Registration Feed

app/Models/Foundation/Summit/Factories/SummitPromoCodeFactory.php, app/Models/Foundation/Summit/Registration/PromoCodes/SummitRegistrationPromoCode.php, app/Models/Foundation/Summit/Registration/PromoCodes/Traits/SpeakersPromoCodeTrait.php, app/Services/Model/Imp/SpeakerService.php, app/Services/Model/Strategies/PromoCodes/AutomaticMultiSpeakerPromoCodeStrategy.php, app/Services/Model/Strategies/PromoCodes/PromoCodeStrategyFactory.php, tests/OAuth2SummitApiTest.php, tests/OAuth2SummitPromoCodesApiTest.php, tests/SpeakerServiceTest.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3270907&stafilter=NotComplete&fileview=grid
=> fix promo code review issues

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitRegistrationInvitationApiController.php, app/Http/Utils/Filters/Filter.php, app/Repositories/Summit/DoctrineSummitRegistrationInvitationRepository.php
Change-Id: I4e296c0f80cd951f2de6010d06913e25df5ca7d8
=> Fixed filters for registration invitations

app/Models/Foundation/Summit/Factories/SummitLocationFactory.php
fix time range population logic
ref https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=3242656
=> Track Chairs Allowed Locations

app/Http/Controllers/Apis/Protected/Summit/Strategies/events/RetrieveSummitEventsStrategy.php, app/Repositories/Summit/DoctrineSummitEventRepository.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3306306&stafilter=NotComplete&fileview=grid
=> new filter by submission_status

app/Http/Controllers/Apis/Protected/Summit/Factories/ExtraQuestionTypeValueValidationRulesFactory.php, app/ModelSerializers/ExtraQuestionTypeValueSerializer.php, app/Models/Foundation/Main/ExtraQuestions/ExtraQuestionType.php, app/Models/Foundation/Main/ExtraQuestions/ExtraQuestionTypeValue.php, app/Models/Foundation/Summit/Factories/SummitOrderExtraQuestionValueFactory.php, app/Services/Model/Imp/ExtraQuestionTypeService.php, database/migrations/model/Version20230608185457.php
* added is_default to values
Change-Id: Iee5fe2e429bdd869bccf4112889c9fe1f996b640
=> Updated Extra Question Types

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitApiController.php, app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitOrderExtraQuestionTypeApiController.php, app/Models/Foundation/Main/Member.php, app/Models/Foundation/Main/SummitAdministratorPermissionGroup.php, database/seeders/ApiEndpointsSeeder.php
"summit-registration-administrators"
to summit auth groups
Change-Id: Ie549661f18038a6fbe2ec1ab0ed7e6e86e241781
=> added new group

app/Services/Model/Imp/SummitService.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3310526&stafilter=NotComplete&fileview=grid
=> event location build fix

app/Http/Controllers/Apis/Protected/Summit/Factories/EventTypeValidationRulesFactory.php, app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitTracksApiController.php, app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitsEventTypesApiController.php, app/ModelSerializers/Summit/SummitEventTypeSerializer.php, app/Models/Foundation/Summit/Defaults/DefaultSummitEventType.php, app/Models/Foundation/Summit/Events/SummitEvent.php, app/Models/Foundation/Summit/Events/SummitEventType.php, app/Models/Foundation/Summit/Events/SummitEventTypeConstants.php, app/Models/Foundation/Summit/Factories/SummitEventTypeFactory.php, app/Models/Foundation/Summit/IPublishableEvent.php, app/Models/Foundation/Summit/ProposedSchedule/SummitProposedScheduleSummitEvent.php, app/Repositories/Summit/DoctrineSummitEventTypeRepository.php, app/Services/Model/Imp/AbstractPublishService.php, app/Services/Model/Imp/SummitMediaUploadTypeService.php, database/migrations/model/Version20230623102958.php, database/migrations/model/Version20230623125135.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3321627&stafilter=NotComplete&fileview=grid
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3321629&stafilter=NotComplete&fileview=grid
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3321630&stafilter=NotComplete&fileview=grid
=> Activity Types - Black Out Time

app/ModelSerializers/Summit/Speakers/AdminPresentationSpeakerSerializer.php, app/Models/Foundation/Summit/Registration/PromoCodes/AssignedPromoCodeSpeaker.php, app/Models/Foundation/Summit/Speakers/PresentationSpeaker.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3322554&stafilter=NotComplete&fileview=grid
=> Speakers Promo Codes - speaker registration codes serialization compatibility

app/Http/Controllers/Apis/Protected/Summit/Factories/PresentationCategoryGroupValidationRulesFactory.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3322552&stafilter=NotComplete&fileview=grid
=> refactoring optional date range validation rules

app/Http/Controllers/Apis/Protected/Summit/Strategies/events/RetrieveSummitEventsStrategy.php, app/Repositories/Summit/DoctrineSummitEventRepository.php, tests/OAuth2SummitEventsApiTest.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3255849&stafilter=NotComplete&fileview=grid
=> presentations filter by media upload with type

app/Repositories/Summit/DoctrineSummitEventRepository.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3255849&stafilter=NotComplete&fileview=grid
=> fix OR filter support

app/Jobs/Emails/ProposedSchedule/SubmitForReviewEmail.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3327231&stafilter=NotComplete&fileview=grid
=> catch the recipient not setted exception as 412

app/Models/Foundation/Summit/SelectionPlan.php, app/Services/Model/Imp/SummitSelectionPlanService.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3325736&stafilter=NotComplete&fileview=grid
=> fix allow_change_requests getter naming

app/Jobs/Emails/EmailTemplatesSchemaSerializerRegistry.php, app/Jobs/Emails/IMailTemplatesConstants.php, app/Jobs/Emails/PresentationSubmissions/SelectionProcess/PresentationSpeakerSelectionProcessExcerptEmail.php, app/Jobs/Emails/PresentationSubmissions/SelectionProcess/PresentationSubmitterSelectionProcessExcerptEmail.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3335406&stafilter=NotComplete&fileview=grid
=> fix email template schema serializer registry

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitEmailEventFlowApiController.php, app/ModelSerializers/Summit/SummitEmailEventFlowSerializer.php, app/Models/Foundation/Summit/EmailFlows/SummitEmailEventFlow.php, app/Models/Foundation/Summit/Summit.php, app/Providers/AppServiceProvider.php, app/Services/Model/Imp/SummitEmailEventFlowService.php, database/migrations/model/Version20230719150524.php
Change-Id: Ie6df13e285ed64bb5a1a4d5fd81491b8b04e7c80
=> Updated Email Flow Event to allow multiple TO recipients

app/Jobs/Emails/IMailTemplatesConstants.php, app/Jobs/Emails/PresentationSubmissions/SelectionProcess/PresentationSpeakerSelectionProcessEmail.php, app/Jobs/Emails/PresentationSubmissions/SelectionProcess/PresentationSubmitterSelectionProcessEmail.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3335406&stafilter=NotComplete&fileview=grid
=> presentations dto schema expand

app/Audit/AuditLogStrategy.php, app/Audit/ConcreteFormatters/ChildEntityFormatters/PresentationSpeakerAssignmentAuditLogFormatter.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3344300&stafilter=NotComplete&fileview=grid
=> speaker assignments audit log

app/Jobs/Emails/IMailTemplatesConstants.php, app/Jobs/Emails/PresentationSubmissions/SelectionProcess/PresentationSpeakerSelectionProcessEmail.php, app/Jobs/Emails/PresentationSubmissions/SelectionProcess/PresentationSubmitterSelectionProcessEmail.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3335406&stafilter=NotComplete&fileview=grid
=> add missing variable definitions

app/Audit/ConcreteFormatters/ChildEntityFormatters/PresentationSpeakerAssignmentAuditLogFormatter.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3344300&stafilter=NotComplete&fileview=grid
Signed-off-by: romanetar [roman_ag@hotmail.com](mailto:roman_ag@hotmail.com)
=> change speaker removal log to match with speaker add log

app/ModelSerializers/Summit/SponsorSerializer.php
ref https://tipit.avaza.com/project/view/332800#!tab=task-pane&groupby=ProjectSection&view=vertical&task=3342953&stafilter=NotComplete&fileview=grid
fix sponsor memberships autz condition
=> QRs enc key by summit

app/Console/Commands/SummitBadgesQREncryptor.php, app/Console/Kernel.php, app/Jobs/EncryptAllSummitBadgeQRCodes.php, app/Models/Foundation/Summit/Registration/Attendees/SummitAttendeeBadge.php, app/Models/Foundation/Summit/Repositories/ISummitAttendeeBadgeRepository.php, app/Repositories/DoctrineRepository.php, app/Repositories/Summit/DoctrineSummitAttendeeBadgeRepository.php, app/Services/Model/ISummitService.php, app/Services/Model/Imp/SummitService.php
ref https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=3343667&stafilter=NotComplete
=> badge qrs regeneration after enc key reset

app/Http/Controllers/Apis/Protected/Summit/Factories/SummitSpeakerEmailsValidationRulesFactory.php, app/Http/Controllers/Apis/Protected/Summit/Factories/SummitSubmittersEmailsValidationRulesFactory.php, app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitAttendeesApiController.php, app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitRegistrationInvitationApiController.php, app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitSpeakersApiController.php, app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitSubmissionInvitationApiController.php, app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitSubmittersApiController.php, app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitTicketApiController.php, app/Http/Utils/Filters/DoctrineInFilterMapping.php, app/Http/Utils/Filters/DoctrineNotInFilterMapping.php, app/Jobs/Emails/PresentationSubmissions/Invitations/ProcessSubmissionsInvitationsJob.php, app/Jobs/Emails/PresentationSubmissions/ProcessSpeakersEmailRequestJob.php, app/Jobs/Emails/PresentationSubmissions/ProcessSubmittersEmailRequestJob.php, app/Jobs/Emails/Registration/Attendees/ProcessAttendeesEmailRequestJob.php, app/Jobs/Emails/Registration/Invitations/ProcessRegistrationInvitationsJob.php, app/Repositories/Summit/DoctrineMemberRepository.php, app/Repositories/Summit/DoctrineSpeakerRepository.php, app/Repositories/Summit/DoctrineSummitAttendeeRepository.php, app/Repositories/Summit/DoctrineSummitAttendeeTicketRepository.php, app/Repositories/Summit/DoctrineSummitRegistrationInvitationRepository.php, app/Repositories/Summit/DoctrineSummitSubmissionInvitationRepository.php, app/Services/Model/AttendeeService.php, app/Services/Model/Imp/SubmitterService.php, app/Services/Model/Imp/SummitRegistrationInvitationService.php, app/Services/Model/Imp/SummitSubmissionInvitationService.php, app/Services/Model/Imp/Traits/ParametrizedSendEmails.php, tests/FilterParserTest.php
Change-Id: I5617245c55baccc9d118c33302484abf201288a4
=> added excluded ids for email sending process

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitSpeakersApiController.php, app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitSubmittersApiController.php, app/Http/Utils/Filters/Filter.php, app/Models/Foundation/Summit/Speakers/PresentationSpeaker.php, app/Repositories/Summit/DoctrineMemberRepository.php, app/Repositories/Summit/DoctrineSpeakerRepository.php, tests/InsertSummitTestData.php, tests/OAuth2SummitSpeakersApiTest.php, tests/OAuth2SummitSubmittersApiTest.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3385040&stafilter=NotComplete&fileview=grid
=> filter speakers and submitters by presentation media uploads

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitTicketApiController.php, app/Repositories/Summit/DoctrineSummitAttendeeTicketRepository.php, app/Services/Model/Imp/SummitOrderService.php, tests/OAuth2SummitTicketsApiTest.php
ref https://tipit.avaza.com/project/view/345732#!tab=task-pane&task=3400809
=> new filter by badge_type_id and new imported fields support

app/Repositories/Summit/DoctrineMemberRepository.php, app/Repositories/Summit/DoctrineSpeakerRepository.php
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3385040&stafilter=NotComplete&fileview=grid
=> add has_media_upload_with_type and has_not_media_upload_with_type explicit filter mappings

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitAttendeesApiController.php, app/Repositories/Summit/DoctrineSummitAttendeeRepository.php, tests/OAuth2AttendeesApiTest.php
Change-Id: Iaa4c557ae3b0b25cb5fe9e8211fca1bc8ce7c946
=> Added tickets_count ordering to GET attendees endpoint

app/Repositories/Summit/DoctrineMemberRepository.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3401583&stafilter=NotComplete&fileview=grid
=> remove restriction for name and last name with nulls

app/Http/Controllers/Apis/Protected/Main/OAuth2ElectionsApiController.php, app/Http/Utils/Filters/Filter.php, app/Repositories/Main/DoctrineElectionsRepository.php, app/Security/ElectionScopes.php, database/seeders/ApiEndpointsSeeder.php, database/seeders/ApiScopesSeeder.php, routes/api_v1.php
GET api/v1/elections
required scope
elections/read
GET api/v1/elections/{election_id}
required scope
elections/read
GET api/v1/elections/{election_id}/candidates
required scope
elections/read
GET api/v1/elections/{election_id}/candidates/gold
required scope
elections/read
Change-Id: I7b5e7100e5e93d7ba27b5dcb120ea1410685c057
=> Added new private elections endpoints

app/Models/Foundation/Summit/Summit.php, app/Services/Model/AttendeeService.php
Change-Id: I85072f876a6dd39413e5b5cd62f658fac93b9979
=> Fixing dupe atttendees FK violation

app/Models/Foundation/Summit/Events/Presentations/Materials/PresentationLink.php, app/Models/Foundation/Summit/Events/Presentations/Materials/PresentationMaterial.php, app/Models/Foundation/Summit/Events/Presentations/Materials/PresentationMediaUpload.php, app/Models/Foundation/Summit/Events/Presentations/Materials/PresentationSlide.php, app/Models/Foundation/Summit/Events/Presentations/Materials/PresentationVideo.php, app/Models/Foundation/Summit/Events/Presentations/Presentation.php, app/Services/Model/Imp/SummitService.php
Change-Id: I7675006f910832d3bcf3ce6b40606774691e10f4
=> Refactoring and tweaks

app/ModelSerializers/Summit/Registration/PromoCodes/SummitRegistrationPromoCodeSerializer.php, app/Models/Foundation/Summit/Registration/PromoCodes/SummitRegistrationPromoCode.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3408495&stafilter=NotComplete&fileview=grid
=> csv remaining column

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitEmailEventFlowApiController.php, app/Repositories/Summit/DoctrineSummitEmailEventFlowRepository.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3414574&stafilter=NotComplete&fileview=grid
=> add order by flow_name support

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitPromoCodesApiController.php, app/Repositories/Summit/DoctrineSpeakersRegistrationDiscountCodeRepository.php, app/Repositories/Summit/DoctrineSpeakersSummitRegistrationPromoCodeRepository.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3383580&stafilter=NotComplete&fileview=grid
=> sorting by email sent and redeemed

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitDocumentsApiController.php, app/Models/Foundation/Summit/SummitDocument.php, app/Services/Model/ISummitDocumentService.php, app/Services/Model/Imp/SummitDocumentService.php, database/seeders/ApiEndpointsSeeder.php, routes/api_v1.php, tests/OAuth2SummitDocumentsApiControllerTest.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3284018&stafilter=NotComplete&fileview=grid
=> new endpoints and tweaks

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitRegistrationInvitationApiController.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3445816&stafilter=NotComplete&fileview=grid
=> export ts fields formatter

app/ModelSerializers/Summit/Registration/SummitAttendeeCSVSerializer.php, tests/OAuth2AttendeesApiTest.php
ref https://tipit.avaza.com/project/view/347916#!tab=task-pane&groupby=ProjectSection&view=vertical&task=3423304&stafilter=NotComplete&fileview=grid
=> add tags column to csv export

app/Models/Foundation/Summit/SummitRegistrationStats.php
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3428567&stafilter=NotComplete&fileview=grid
=> refunded amount without taxes

app/Models/Foundation/Summit/Factories/SummitPromoCodeFactory.php, app/Models/Foundation/Summit/Registration/PromoCodes/SummitRegistrationPromoCode.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3465497&stafilter=NotComplete&fileview=grid
=> allows unassign ticket types from promocodes

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitPromoCodesApiController.php, app/Services/Model/ISummitPromoCodeService.php, app/Services/Model/Imp/SummitPromoCodeService.php, app/Services/Model/Strategies/PromoCodes/IPromoCodeValidationStrategy.php, app/Services/Model/Strategies/PromoCodes/IPromoCodeValidationStrategyFactory.php, app/Services/Model/Strategies/PromoCodes/PrePaidTicketTypePromoCodeValidationStrategy.php, app/Services/Model/Strategies/PromoCodes/PromoCodeValidationStrategyFactory.php, app/Services/Model/Strategies/PromoCodes/RegularTicketTypePromoCodeValidationStrategy.php, database/seeders/ApiEndpointsSeeder.php, routes/api_v1.php, tests/OAuth2SummitPromoCodesApiTest.php
https://tipit.avaza.com/project/view/347915#!tab=task-pane&groupby=ProjectSection&view=vertical&task=3471008&stafilter=NotComplete&fileview=grid
=> pre validate pc

resources/views/speakers/edit_permissions/approved.blade.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3017821&stafilter=NotComplete&fileview=grid
=> After allow message tweak

app/Models/Foundation/Summit/Registration/PromoCodes/Traits/SpeakersPromoCodeTrait.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3442745&stafilter=NotComplete&fileview=grid
=> fix isRedeemed when no speakers assigned

app/Http/Controllers/Apis/Protected/Summit/Factories/EventTypeValidationRulesFactory.php, app/Http/Controllers/Apis/Protected/Summit/Factories/SummitEventValidationRulesFactory.php, app/ModelSerializers/Summit/SummitEventSerializer.php, app/ModelSerializers/Summit/SummitEventTypeSerializer.php, app/Models/Foundation/Summit/Events/SummitEvent.php, app/Models/Foundation/Summit/Events/SummitEventType.php, app/Models/Foundation/Summit/Factories/SummitEventFactory.php, app/Models/Foundation/Summit/Factories/SummitEventTypeFactory.php, app/Services/Model/Imp/SummitEventTypeService.php, app/Services/Model/Imp/SummitService.php, database/migrations/model/Version20240205201840.php, database/migrations/model/Version20240205201841.php
added to event types/events new collection allowed_ticket_types
Change-Id: I6924ab6e1c4d4016c7e9af3b9053d742e4ce516f
=> feat: schedule per ticket type

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitPromoCodesApiController.php, app/Repositories/Summit/DoctrineSummitRegistrationPromoCodeRepository.php, config/doctrine.php, tests/OAuth2SummitPromoCodesApiTest.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3488006&stafilter=NotComplete&fileview=grid
=> new order param: redeemed

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitBadgeScanApiController.php, app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitSponsorApiController.php, app/ModelSerializers/Summit/SponsorSerializer.php, app/Models/Foundation/Main/Member.php, app/Models/Foundation/Main/Strategies/MemberSummitStrategyFactory.php
Change-Id: I472cc435137fbab71a567dd6277bade91bdc0813
=> chore: refactored authz

app/Console/Commands/EventBritePromoCodesRedeemProcessor.php, app/Console/Kernel.php, app/Models/Foundation/Summit/Registration/PromoCodes/SummitRegistrationPromoCode.php, database/migrations/model/Version20240320151845.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3488006&stafilter=NotComplete&fileview=grid
=> fix: add setRedeem trigger at add/remove promocode usage and sync migra

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitsTicketTypesApiController.php, app/Models/Foundation/Summit/Registration/SummitTicketType.php, app/Models/Foundation/Summit/Summit.php, app/Services/Model/ISummitTicketTypeService.php, app/Services/Model/Imp/SummitTicketTypeService.php, database/seeders/ApiEndpointsSeeder.php, routes/api_v1.php, tests/OAuth2SummitTicketTypesApiTest.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3522347&stafilter=NotComplete&fileview=grid
=> feat: new endpoint for currency symbol update

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitPromoCodesApiController.php, app/Http/Utils/CSV/EpochCellFormatter.php, tests/OAuth2PromoCodesApiTest.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3408495&stafilter=NotComplete&fileview=grid
=> feat: add tz name to created and updated columns

app/Http/Controllers/Apis/Protected/Summit/Factories/LeadReportSettingsValidationRulesFactory.php, app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitApiController.php, app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitSponsorApiController.php, app/ModelSerializers/SerializerRegistry.php, app/ModelSerializers/Summit/Registration/SponsorBadgeScanCSVSerializer.php, app/ModelSerializers/Summit/SponsorSerializer.php, app/ModelSerializers/Summit/SummitLeadReportSettingSerializer.php, app/ModelSerializers/Summit/SummitSerializer.php, app/Models/Foundation/Summit/Factories/LeadReportSettingsFactory.php, app/Models/Foundation/Summit/Sponsor.php, app/Models/Foundation/Summit/Summit.php, app/Models/Foundation/Summit/SummitLeadReportSetting.php, app/Providers/AppServiceProvider.php, app/Services/Model/ISummitService.php, app/Services/Model/ISummitSponsorService.php, app/Services/Model/Imp/SummitService.php, app/Services/Model/Imp/SummitSponsorService.php, database/migrations/model/Version20240319123214.php, database/seeders/ApiEndpointsSeeder.php, routes/api_v1.php, tests/OAuth2SummitApiTest.php, tests/OAuth2SummitBadgeScanApiControllerTest.php, tests/OAuth2SummitSponsorApiTest.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3519134&stafilter=NotComplete&fileview=grid
ref https://tipit.avaza.com/project/view/347915#!tab=task-pane&groupby=ProjectSection&view=vertical&task=3523370&stafilter=NotComplete&fileview=grid
=> feat: Badge Scan Export Filters Presettings

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitPromoCodesApiController.php, app/Services/Model/ISummitPromoCodeService.php, app/Services/Model/Imp/SummitPromoCodeService.php, database/seeders/ApiEndpointsSeeder.php, routes/api_v1.php
POST /api/v1/summits/{id}/sponsor-promo-codes/csv
params
file
Change-Id: I5b9b50d548d63cc22dd20ba19150fb94e3e02ae9
=> feat: add new endpoint to ingest sponsor promo codes

app/Repositories/Summit/DoctrineSummitEventRepository.php
ref https://tipit.avaza.com/project/view/347915#!tab=task-pane&groupby=ProjectSection&view=vertical&task=3532562&stafilter=NotComplete&fileview=grid
=> fix: selection_status order mapping

app/Http/Controllers/Apis/Protected/Summit/Strategies/events/RetrieveSummitEventsStrategy.php, app/Repositories/Summit/DoctrineSummitEventRepository.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3495445&stafilter=NotComplete&fileview=grid
=> feat: presentation progress_flags sorting support

app/ModelSerializers/Companies/BaseCompanySerializer.php, app/ModelSerializers/Marketplace/CompanyServiceSerializer.php, app/Models/Foundation/Main/Companies/Company.php, app/Models/Foundation/Marketplace/Appliance.php, app/Models/Foundation/Marketplace/CloudService.php, app/Models/Foundation/Marketplace/CompanyService.php, app/Models/Foundation/Marketplace/Consultant.php, app/Models/Foundation/Marketplace/Distribution.php, app/Models/Foundation/Marketplace/OpenStackImplementation.php, app/Models/Foundation/Marketplace/PrivateCloudService.php, app/Models/Foundation/Marketplace/PublicCloudService.php, app/Models/Foundation/Marketplace/RegionalSupportedCompanyService.php, app/Models/Foundation/Marketplace/RemoteCloudService.php, app/Models/Foundation/Marketplace/TrainingService.php
ref https://tipit.avaza.com/project/view/188885#!tab=task-pane&task=3538025
=> feat: expose new service and company fields

app/ModelSerializers/Marketplace/CompanyServiceSerializer.php, app/Models/Foundation/Main/Companies/Company.php
ref https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=3538025&stafilter=NotComplete
=> fix: company service serializer expand/fields/relations logic fix

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitAttendeesApiController.php, app/Repositories/Summit/DoctrineSummitAttendeeRepository.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3555897&stafilter=NotComplete&fileview=grid
=> feat: attendee notes filter and sort

app/Http/Utils/Filters/FilterElement.php, tests/FilterParserTest.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3544153&stafilter=NotComplete&fileview=grid
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3544163&stafilter=NotComplete&fileview=grid
=> feat: add support for %NULL% and %EMPTY% filter tokens

app/Repositories/Summit/DoctrineSummitEventRepository.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3495445&stafilter=NotComplete&fileview=grid
=> fix: action order criteria

app/Http/Controllers/Apis/Protected/Summit/Factories/SummitMediaUploadTypeValidationRulesFactory.php, database/migrations/model/Version20240514115129.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3559303&stafilter=NotComplete&fileview=grid
=> feat: description field length increase

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitAttendeesApiController.php, app/Jobs/Emails/Registration/Attendees/ProcessAttendeesEmailRequestJob.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3555897&stafilter=NotComplete&fileview=grid
=> fix: added attendee notes filter at send stage

app/Models/Foundation/Summit/Summit.php, database/migrations/model/Version20240514134802.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3498865&stafilter=NotComplete&fileview=grid
=> feat: slug prefix generation strategy update

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitPromoCodesApiController.php, app/ModelSerializers/Summit/Registration/PromoCodes/SummitRegistrationDiscountCodeCSVSerializerTrait.php, app/ModelSerializers/Summit/Registration/PromoCodes/SummitRegistrationPromoCodeCSVSerializerTrait.php, app/Models/Foundation/Summit/Registration/PromoCodes/SummitRegistrationPromoCode.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3408495&stafilter=NotComplete&fileview=grid
=> fix: export tz and unlimited remaining

app/Http/Controllers/Apis/Protected/Summit/Strategies/events/RetrieveSummitEventsStrategy.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3584163&stafilter=NotComplete&fileview=grid
=> feat: allow event filtering and sorting by created and last_edited

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitTicketApiController.php
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3586596&stafilter=NotComplete&fileview=grid
=> fix: ticket list dates in show tz

app/Http/Controllers/Apis/Protected/Summit/Factories/SummitValidationRulesFactory.php, app/Models/Foundation/Summit/Events/Presentations/Presentation.php, app/Models/Foundation/Summit/Factories/SummitFactory.php, app/Models/Foundation/Summit/Registration/Attendees/SummitAttendee.php, app/Models/Foundation/Summit/Registration/SponsorBadgeScan.php, app/Models/Foundation/Summit/Repositories/ISummitRepository.php, app/Models/Foundation/Summit/Summit.php, app/Repositories/Summit/DoctrineSummitRepository.php, app/Services/Model/Imp/SummitService.php, tests/InsertSummitTestData.php, tests/OAuth2SummitApiTest.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3572465&stafilter=NotComplete&fileview=grid
=> feat: registration slug prefix manual set up

app/Models/Foundation/Main/Companies/SponsoredProject.php, app/Models/Foundation/Main/Member.php, app/Models/Foundation/Summit/Events/Presentations/TrackChairs/SummitTrackChair.php, app/Models/Foundation/Summit/Events/Presentations/TrackQuestions/TrackMultiValueQuestionTemplate.php, app/Models/Foundation/Summit/Events/RSVP/Templates/RSVPMultiValueQuestionTemplate.php, app/Models/Foundation/Summit/Events/RSVP/Templates/RSVPTemplate.php, app/Models/Foundation/Summit/SelectionPlan.php, app/Models/Foundation/Summit/Sponsor.php, app/Models/Foundation/Summit/SummitScheduleConfig.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3321351&stafilter=NotComplete&fileview=grid
Signed-off-by: romanetar [roman_ag@hotmail.com]
=> refactor: Criteria boolean filter values and return warnings fixes

app/Http/Controllers/Apis/Protected/Summit/Factories/SummitEventValidationRulesFactory.php, app/Http/Controllers/Apis/Protected/Summit/Strategies/events/RetrieveSummitEventsStrategy.php, app/ModelSerializers/Summit/SummitEventSerializer.php, app/Models/Foundation/Summit/Events/SummitEvent.php, app/Models/Foundation/Summit/Factories/PresentationFactory.php, app/Models/Foundation/Summit/Factories/SummitEventFactory.php, app/Repositories/Summit/DoctrineSummitEventRepository.php, create_migration.sh, database/migrations/model/Version20240625172824.php, database/migrations/model/Version20240625175839.php, tests/InsertSummitTestData.php, tests/OAuth2PresentationSubmissionTest.php, tests/OAuth2SummitEventsApiTest.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3584165&stafilter=NotComplete&fileview=grid
=> feat: new SummitEvent field submission_source

database/migrations/model/Version20240625172824.php, database/migrations/model/Version20240625175839.php
ref https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=3584165&stafilter=NotComplete
=> fix: change to admin as the default submission source

app/Models/Foundation/Summit/Summit.php, tests/OAuth2SummitTicketTypesApiTest.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3587575&stafilter=NotComplete&fileview=grid
=> fix: initial value in determining currency

app/Http/Controllers/Apis/Protected/Summit/Factories/SummitSelectionPlanValidationRulesFactory.php, app/ModelSerializers/Summit/SelectionPlanSerializer.php, app/Models/Foundation/Summit/Factories/SummitSelectionPlanFactory.php, app/Models/Foundation/Summit/SelectionPlan.php, app/Repositories/Summit/DoctrineSelectionPlanRepository.php, database/migrations/model/Version20240627160838.php, tests/OAuth2SummitSelectionPlansApiTest.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3472422&stafilter=NotComplete&fileview=grid
=> feat: hidden selection plan support

database/migrations/model/Version20240702124106.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3572465&stafilter=NotComplete&fileview=grid
=> fix: format former prefix before compare

.env.example, app/Jobs/Emails/AbstractSummitEmailJob.php, config/marketing.php
ref https://tipit.avaza.com/project/view/203215#!tab=task-pane&task=3589655
=> feat: inject default email template vars

app/Console/Commands/PublishStreamUpdatesCommand.php, app/Console/Kernel.php, app/Models/Foundation/Summit/Events/SummitEvent.php, app/Models/Foundation/Summit/Summit.php, app/Services/Model/ISummitService.php, app/Services/Model/Imp/SummitService.php, routes/api_v1.php
ref https://tipit.avaza.com/project/view/359044#!tab=task-pane&groupby=ProjectSection&view=vertical&task=3629381&stafilter=NotComplete&fileview=grid
=> feat: add time checking to summit event serializing for streaming info

app/Console/Commands/PurgeSummitsMarkAsDeletedCommand.php, app/Console/Kernel.php, app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitApiController.php, app/Models/Foundation/Summit/Repositories/ISummitAttendeeRepository.php, app/Models/Foundation/Summit/Repositories/ISummitEventRepository.php, app/Models/Foundation/Summit/Repositories/ISummitLocationRepository.php, app/Models/Foundation/Summit/Repositories/ISummitOrderRepository.php, app/Models/Foundation/Summit/Repositories/ISummitRegistrationInvitationRepository.php, app/Models/Foundation/Summit/Summit.php, app/Repositories/Summit/DoctrineSummitAttendeeRepository.php, app/Repositories/Summit/DoctrineSummitEventRepository.php, app/Repositories/Summit/DoctrineSummitLocationRepository.php, app/Repositories/Summit/DoctrineSummitOrderRepository.php, app/Repositories/Summit/DoctrineSummitRegistrationInvitationRepository.php, app/Repositories/Summit/DoctrineSummitRepository.php, app/Services/Model/Imp/SummitService.php, database/migrations/model/Version20240913183703.php
mark summit for deletion and a background job will do the rest.
=> fix: add background deleting mechanism for summit

app/Models/Foundation/Summit/Locations/SummitBookableVenueRoom.php, app/Models/Foundation/Summit/Locations/SummitBookableVenueRoomAttributeValue.php, app/Models/Foundation/Summit/Locations/SummitVenue.php, app/Models/Foundation/Summit/Summit.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3646033&stafilter=NotComplete&fileview=grid
=> fix: location room attributes cloning

app/Jobs/Emails/AbstractSummitEmailJob.php, app/Jobs/Emails/Registration/Attendees/AbstractSummitAttendeeTicketEmail.php, app/Jobs/Emails/Registration/Attendees/SummitAttendeeTicketEmail.php
ref https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=3677655&stafilter=NotComplete
=> fix: new variable for venue address in email ticket template

app/Models/Foundation/Summit/Factories/SummitAttendeeFactory.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3676422&stafilter=NotComplete&fileview=grid
=> fix: allow clearing disclaimer accepted date

Libs/Utils/HTMLCleaner.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3687092&stafilter=NotComplete&fileview=grid
=> fix: allow text-align property

app/Models/Foundation/Main/SummitAdministratorPermissionGroup.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3689975&stafilter=NotComplete&fileview=grid
=> fix: show member's email in validation message

app/Models/Foundation/Summit/SelectionPlan.php, app/Services/Model/Imp/PresentationService.php
ref https://tipit.avaza.com/project/view/360253#!tab=task-pane&groupby=ProjectSection&view=vertical&task=3586507&stafilter=NotComplete&fileview=grid
=> fix: relax check allowed questions

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitOrdersApiController.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3672584&stafilter=NotComplete&fileview=grid
=> feat: make owner_company optional

routes/public_api.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3720004&stafilter=NotComplete&fileview=grid
=> feat: new get company by id public endpoint

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitSponsorApiController.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3738274&stafilter=NotComplete&fileview=grid
=> feat: check if current_member is null before checking if is authorized

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitSponsorApiController.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3751322&stafilter=NotComplete&fileview=grid
=> fix: is_authz logic error

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitSponsorApiController.php, app/Repositories/Summit/DoctrineSponsorRepository.php, tests/OAuth2SummitSponsorApiTest.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3756058&stafilter=NotComplete&fileview=grid
=> feat: new order criteria

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitEventsApiController.php, app/Models/Foundation/Summit/Events/Presentations/Presentation.php, app/Services/Model/ISummitService.php, app/Services/Model/Imp/SummitService.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3742548&stafilter=NotComplete&fileview=grid
=> feat: add submission closed validation

config/doctrine.php
ref https://tipit.avaza.com/project/view/376250#!tab=task-pane&groupby=ProjectSection&view=vertical&task=3806798&stafilter=NotComplete&fileview=grid
=> fix: doctrine logger error

Libs/Utils/RequestUtils.php, app/Http/Middleware/OAuth2BearerAccessTokenRequestValidator.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3817599&stafilter=NotComplete&fileview=grid
=> feat: referer -> origin fallback

app/ModelSerializers/Summit/SponsorSerializer.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3817798&stafilter=NotComplete&fileview=grid
=> refactor: remove field qr_codes_enc_key from SponsorSerializer

app/Http/Controllers/Apis/Protected/Main/OAuth2MembersApiController.php, app/Http/Utils/PagingResponse.php, app/Models/Foundation/Main/Repositories/IMemberRepository.php, app/Repositories/Summit/DoctrineMemberRepository.php, routes/public_api.php, tests/InsertMemberTestData.php, tests/OAuth2MembersApiTest.php
ref https://tipit.avaza.com/project/view/376250#!tab=task-pane&task=3819121
GET api/v1/public/members/all/companies
=> feat: add new endpoint to get member companies

app/ModelSerializers/Summit/SponsorSerializer.php
Reverts OpenStackweb/summit-api#316
=> Revert "refactor: remove field qr_codes_enc_key from SponsorSerializer"

app/Http/Controllers/Apis/Protected/Summit/OAuth2SummitApiController.php, app/Models/Foundation/Main/IGroup.php, app/Services/Model/ISummitService.php, app/Services/Model/Imp/SummitService.php, database/seeders/ApiEndpointsSeeder.php, routes/api_v1.php, tests/OAuth2SummitApiTest.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3817803&stafilter=NotComplete&fileview=grid
=> feat: badge qr code validation endpoint

app/Http/Controllers/Apis/Protected/Summit/Factories/SponsorValidationRulesFactory.php, app/Models/Foundation/Summit/Sponsor.php, app/Providers/AppServiceProvider.php, app/Services/Model/Imp/SummitSponsorService.php, tests/OAuth2SummitSponsorApiTest.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3826676&stafilter=NotComplete&fileview=grid
=> feat: sponsors crud new sponsorship collection

app/Console/Commands/IngestSummitOrderPaymentInfoCommand.php, app/Console/Kernel.php, app/Jobs/Emails/IMailTemplatesConstants.php, app/Jobs/Emails/Registration/RegisteredMemberOrderPaidMail.php, app/ModelSerializers/Summit/Registration/SummitOrderReservationSerializer.php, app/Models/Foundation/Summit/Registration/SummitOrder.php, app/Models/Foundation/Summit/Repositories/ISummitOrderRepository.php, app/Repositories/Summit/DoctrineSummitOrderRepository.php, app/Services/Apis/IPaymentGatewayAPI.php, app/Services/Apis/PaymentGateways/LawPayApi.php, app/Services/Apis/PaymentGateways/StripeApi.php, app/Services/Model/ISummitOrderService.php, app/Services/Model/Imp/SummitOrderService.php, database/migrations/model/Version20250731013533.php
ref https://tipit.avaza.com/task#task=3841791
=> feat: add generic parsing of payment method info at summit order

app/Models/Foundation/Main/Member.php
ref https://app.clickup.com/t/86b6dbuh5
chore: remove index hinting from member queries
refactor: immprove getPaidSummitTicketsBySummitId method
=> fix: remove index hinting from SQL raw

config/database.php, config/doctrine.php, start_local_server.sh
ref: https://app.clickup.com/t/86b6erkmc
chore: create an only write connection for migrations
=>  feature/create-model-write-conn

app/Audit/AuditLogStrategy.php, app/Audit/ILogger.php, app/Audit/Loggers/SummitAttendeeBadgeAuditLogger.php, app/Audit/Loggers/SummitEventAuditLogger.php, app/Http/Controllers/Apis/Protected/Main/OAuth2AuditLogController.php, app/ModelSerializers/Audit/AuditLogSerializer.php, app/Models/Foundation/Main/Audit/AuditLog.php, app/Models/Foundation/Main/Audit/SummitAuditLog.php, app/Models/Foundation/Main/Audit/SummitEventAuditLog.php, app/Repositories/Main/DoctrineAuditLogRepository.php, database/migrations/model/Version20250905124424.php, tests/AuditModelTest.php, tests/OAuth2AuditLogApiTest.php
ref https://app.clickup.com/t/86b6jb4u1
=> feat: add metadata field to AuditLog model
